### ISSUE TITLE
10.12.2019 To-Do

### ISSUE THREAD

**Issue by deepanjan1** [deepanjan1/tts-api#1]
- [x] re-factor database code; place `db_helpers.py` into model class
- [ ] consolidate `tts.py` and `authenticate.py` into one utilities directory
- [x] implement flask blueprint
- [ ] look at options to not use pocket API for text scraping; will need some version of BeautifulSoup4

**Comment by deepanjan1** [comment]
- [x] add `app/` directory and `__init__.py` to properly set up database

**Comment by deepanjan1** [comment]
- [x] should I consider Docker?

**Comment by deepanjan1** [comment]
> * [x]  should I consider Docker?

Not considering Docker.  Feels like it's over complicating this solution.
